ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('Servicios.urls')),
    path('', include('ProyectoWebApp.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),

]

ProyectoWebApp/urls.py
from django.urls import path

from ProyectoWebApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('',views.home,name="Home"),
    
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Servicios/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('',views.servicios,name="Servicios"),
    
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
      
    path('',views.blog,name="Blog"),
    path('categoria/<categoria_id>/',views.categoria, name="categoria"),
    
]

carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [

    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
    
]

contacto/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('',views.contacto,name="Contacto"),
    
]

tienda/urls.py
from django.urls import path

from .import views


urlpatterns = [
    
    
    path('',views.tienda,name="Tienda"),
    
]

ProyectoWebApp/models.py
from django.db import models

# Create your models here.

Servicios/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    titulo=models.CharField(max_length=50)
    contenido=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to='servicios')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='servicio'
        verbose_name_plural='servicios'

    def __str__(self):
        return self.titulo

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Categoria(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='categoria'
        verbose_name_plural='gategorias'

    def __str__(self):
        return self.nombre
    
class Post(models.Model):
    titulo=models.CharField(max_length=50)
    contenido=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to='blog',null=True, blank=True)
    autor=models.ForeignKey(User,on_delete=models.CASCADE)
    categorias=models.ManyToManyField(Categoria)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='post'
        verbose_name_plural='posts'

    def __str__(self):
        return self.titulo
    

carro/models.py
from django.db import models

# Create your models here.

contacto/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name="producto"
        verbose_name_plural="productos"
    
    def __str__(self):
        return self.nombre
    

contacto/forms.py
from django import forms

class FormularioContacto(forms.Form):
    
    nombre=forms.CharField(label='Nombre', required=True)
    email=forms.CharField(label='Email', required=True)
    contenido=forms.CharField(label='Contenido', widget=forms.Textarea, required=False)    
    
    
    
    
    #your_name = forms.CharField(label='Your name', max_length=100)

ProyectoWebApp/views.py
from django.shortcuts import render, HttpResponse
#importamos Servicio de la app servicios en el archivo models


# Create your views here.

def home(request):

    return render(request, "ProyectoWebApp/home.html")

Servicios/views.py
from django.shortcuts import render

from Servicios.models import Servicio
# Create your views here.

def servicios(request):

    servicios=Servicio.objects.all()
    
    return render(request, "Servicios/servicios.html", {"servicios":servicios})

blog/views.py
from django.shortcuts import render
from blog.models import Post,Categoria

# Create your views here.

def blog(request):
    
    posts= Post.objects.all()
    return render(request, "blog/blog.html", {"posts":posts} )

def categoria(request,categoria_id):

    categoria=Categoria.objects.get(id=categoria_id)
    posts=Post.objects.filter(categorias=categoria)
    return render(request,"blog/categoria.html", {"categoria":categoria,"posts":posts})

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)

    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)

    return redirect("Tienda")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)

    return redirect("Tienda")
    
def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()

    return redirect("Tienda")

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto
from django.core.mail import EmailMessage

# Create your views here.

def contacto(request):
    
    formulario_contacto=FormularioContacto()

    if request.method=="POST":
        formulario_contacto=FormularioContacto(data=request.POST)
        if formulario_contacto.is_valid():
            nombre=request.POST.get("nombre")
            email=request.POST.get("email")
            contenido=request.POST.get("contenido")

            email=EmailMessage("Mensaje desde app Django",
            "El usuario con nombre:{} con la direccion {} escribe lo siguiente: \n\n {}".format(nombre,email,contenido),
            "",["wbayona123@gmail.com"],reply_to=[email])

            try:
                email.send()

                return redirect("/contacto/?valido")

            except:
                return redirect("/contacto/?novalido")

    return render(request, "contacto/contacto.html",{'miFormulario':formulario_contacto})

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda(request):
    
    productos=Producto.objects.all()
    return render(request, "tienda/tienda.html",{"productos":productos})

ProyectoWebApp/templates/ProyectoWebApp/base.html
<html>

<head>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'ProyectoWebApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'ProyectoWebApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower"><img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/logo.png' %}" width="200" height="200">Vampi Market</span>
      </h1>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Home' %}"><img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/logo.png' %}" width="100" height="100">Vampi Market</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {%if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}">Inicio</a>
          </li>
          <li class="nav-item {%if request.path == '/servicios/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Servicios' %}">Servicios</a>
          </li>
          <li class="nav-item {%if request.path == '/tienda/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {%if request.path == '/contacto/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Contacto' %}">Contacto</a>
          </li>
          <li class="nav-item {%if request.path|slice:':6' == '/blog/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Blog' %}">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>


   <!-- Contenido Cambiante -->
{% block content %}

  
    
{% endblock %}

    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2021</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'ProyectoWebApp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ProyectoWebApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

ProyectoWebApp/templates/ProyectoWebApp/home.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/principal2.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Atención Personalizada</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">Tenemos los mejores productos a tu disposición!!!. Comunícate con nosotros al 987-414121 o al 923 935368
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 15 años de experiencia y la mejor red de proveedores que nos permite brindarte productos y servicios con total calidad!! Llámanos y disfrútalos!!!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

Servicios/templates/servicios/servicios.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

    {% for servicio in servicios %}

    <section class="page-section clearfix">
        <div class="container">
          <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{servicio.imagen.url}}" alt="" style="width:50%;">
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
              <h2 class="section-heading mb-4" >
                <span class="section-heading-lower">{{servicio.titulo}}</span>
                <span class="section-heading-upper">{{servicio.contenido}}</span>
              </h2>
                           
            </div>
          </div>
        </div>
      </section>

    {% endfor %}

{% endblock %}

blog/templates/blog/blog.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

    {% for post in posts %}

    <section class="page-section clearfix">
        <div class="container">
          <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width:50%;">
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
              <h2 class="section-heading mb-4" >
                <span class="section-heading-lower">{{post.titulo}}</span>
                <span class="section-heading-upper">{{post.contenido}}</span>
                
              </h2>
                <div style="text-align: left; font-size: 80%;" >
                    Autor: {{post.autor}}
                </div>  

            </div>
          </div>
        </div>
      </section>

    {% endfor %}

    <section>

        <div style="width: 75%; margin: auto; text-align: center; color: white;">
            
            Categorias: 

            {% for post in posts %}

                {% for categoria in post.categorias.all %}

                    <a href="{% url 'categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}} </a> &nbsp;&nbsp;&nbsp;

                {% endfor %}
            
            {% endfor %}
        </div>

    </section>
{% endblock %}

blog/templates/blog/categoria.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

    {% for post in posts %}

    <section class="page-section clearfix">
        <div class="container">
          <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width:50%;">
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
              <h2 class="section-heading mb-4" >
                <span class="section-heading-lower">{{post.titulo}}</span>
                <span class="section-heading-upper">{{post.contenido}}</span>
                
              </h2>
                <div style="text-align: left; font-size: 80%;" >
                    Autor: {{post.autor}}
                </div>  

            </div>
          </div>
        </div>
      </section>

    {% endfor %}

    <section>

        <div style="width: 75%; margin: auto; text-align: center; color: white;">
            
            Categorias: 

            {% for post in posts %}

                {% for categoria in post.categorias.all %}

                    {{categoria.nombre}} &nbsp;&nbsp;&nbsp;

                {% endfor %}
            
            {% endfor %}
        </div>

    </section>
{% endblock %}

contacto/templates/contacto/contacto.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

<div class="contenedorFormulario">

    {% if "valido" in request.GET %}

        <p style="color: white;">La información se ha guardado correctamente</p>

    {% endif%}

    <form action="" method="POST" style="text-align: center;">
        {% csrf_token %}
        <table style="color: white; margin: 20px auto;">{{miFormulario.as_table}}
        </table>

        <input type="submit" value="Enviar" style="width: 150px;">
        
    </form>
    
</div>

{% endblock %}

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>

        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>

    </thead>

    <tbody>
        
        {% if request.session.carro.items %}
            
            {% for key, value in request.session.carro.items %}

                <tr class="text-center">
                    <td>{{value.nombre}}</td>  
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success" >+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success" >-</a><br/>

                        S/. {{value.precio}}
                    </td>  

                </tr>

            {% endfor %}
        
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">Sin productos</div>
                    
                </td>
            </tr>

        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                <p style="color: white;">Total: S/ {{importe_total_carro}}</p>
            </td>

        </tr>

    </tfoot>

    

</table>

tienda/templates/tienda/tienda.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}


{% block content %}

<div class="container">

    <div style ="float:right;">
        
        {% include "carro/widget.html" %}

    </div>

    <div class="row">

{% for producto in productos %}

    <div class="col-md-3">
        <div class="card" style="width: 100%; margin: 5px 5px;">
                <img src="{{producto.imagen.url}}" class="card-img-top">

                <div class="card-body" style="text-align: center;">

                    <h7 class="card-title">{{producto.nombre}}</h7>

                    <p class="card-text">S/&nbsp;{{producto.precio}}</p>
                    
                    
                
                </div>

                <div class="card-footer text-center">
                
                    <a href ="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
                    

                </div>
        </div>
    </div>
        

{% endfor %}
    </div>
</div>

{% endblock  %}